{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "#                             Plant disease detection"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [],
   "source": [
    "import numpy as np\n",
    "import matplotlib.pyplot as plt\n",
    "import os\n",
    "import tensorflow as tf\n",
    "from tensorflow.keras.preprocessing.image import ImageDataGenerator\n",
    "#technique that can be used to artificially expand the size of a training dataset by creating modified versions of images in the dataset\n",
    "from tensorflow.keras.layers import Dense, Input, Dropout,Flatten, Conv2D # cnn \n",
    "#batch normaliztion is a technique to improve the learning rates of the model by normalizing the input layers.\n",
    "#Normalization is a technique applied during data preparation so as to change the \n",
    "#values of numeric columns in the dataset to use a common scale.\n",
    "\n",
    "#where one feature might be fractional and range between zero and one, and another might range between zero and a thousand.\n",
    "#activation:function that is added into an artificial neural network in order to help the network learn complex patterns in the data.\n",
    "\n",
    "# it reduces the number of parameters to learn and the amount of computation performed in the network. \n",
    "from tensorflow.keras.layers import BatchNormalization, Activation, MaxPooling2D\n",
    "#it reduces the number of parameters to learn and the amount of \n",
    "# computation performed in the network. feature reduction.\n",
    "#model represents the actual neural network model.\n",
    "##A Sequential model is appropriate for a plain stack of layers where each layer has exactly one input tensor and one output tensor\n",
    "from tensorflow.keras.models import Model, Sequential\n",
    "\n",
    "#Adam is an optimization algorithm that can be used instead of the classical stochastic gradient descent procedure to update network weights iterative based in training data.\n",
    "from tensorflow.keras.optimizers import Adam\n",
    "\n",
    "from tensorflow.keras.callbacks import ModelCheckpoint, ReduceLROnPlateau\n",
    "#ReduceLROnPlateau is a callback to reduce the learning rate when a metric has stopped improving.\n",
    "# Converts a Keras model to dot format and save to a file.\n",
    "from tensorflow.keras.utils import plot_model\n",
    "from IPython.display import SVG, Image # to view 2d data to image."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "917 Pepper__bell___Bacterial_spot images\n",
      "1402 Pepper__bell___healthy images\n",
      "927 Potato___Early_blight images\n",
      "127 Potato___healthy images\n",
      "919 Potato___Late_blight images\n",
      "2017 Tomato_Bacterial_spot images\n",
      "919 Tomato_Early_blight images\n",
      "1494 Tomato_healthy images\n",
      "1816 Tomato_Late_blight images\n",
      "879 Tomato_Leaf_Mold images\n",
      "1682 Tomato_Septoria_leaf_spot images\n",
      "1603 Tomato_Spider_mites_Two_spotted_spider_mite images\n",
      "1307 Tomato__Target_Spot images\n",
      "308 Tomato__Tomato_mosaic_virus images\n",
      "3068 Tomato__Tomato_YellowLeaf__Curl_Virus images\n"
     ]
    }
   ],
   "source": [
    "# For checking out that how many images are available in the train set we can use import OS\n",
    "for types in os.listdir(\"PlantVillage/My Drive/train_set/\"):\n",
    "    print(str(len(os.listdir(\"PlantVillage/My Drive/train_set/\"+ types)))+\" \"+ types+' images')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Found 19384 images belonging to 15 classes.\n",
      "Found 1254 images belonging to 15 classes.\n"
     ]
    }
   ],
   "source": [
    "\n",
    "# Complete Dataset images can be loaded using ImageDataGenerator function\n",
    "img_size=48\n",
    "batch_size=64 # per batch 64 images processed.\n",
    "datagen_train=ImageDataGenerator(horizontal_flip=True) # loading of images.\n",
    "train_generator=datagen_train.flow_from_directory(\"PlantVillage/My Drive/train_set\",\n",
    "target_size=(img_size,img_size),\n",
    "batch_size=batch_size,\n",
    "class_mode='categorical',\n",
    "shuffle=True)\n",
    "\n",
    "# testing data.\n",
    "datagen_test=ImageDataGenerator(horizontal_flip=True)\n",
    "validation_generator=datagen_test.flow_from_directory(\"PlantVillage/My Drive/test_data\",\n",
    "target_size=(img_size,img_size),\n",
    "batch_size=batch_size,\n",
    "class_mode='categorical',\n",
    "shuffle=True)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {},
   "outputs": [],
   "source": [
    "import pickle\n",
    "saved_model = pickle.dumps(train_generator.class_indices)\n",
    "with open('train_gen', 'wb') as files:\n",
    "    pickle.dump(saved_model, files)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {},
   "outputs": [],
   "source": [
    "detection=Sequential()\n",
    "# Sequential model\n",
    "# adding various layers.\n",
    "#1 -convolutional layer-1\n",
    "#we are definig layers.\n",
    "detection.add(Conv2D(64,(3,3),padding='same',input_shape=(48,48,3)))\n",
    "\n",
    "#The padding tells us what happens when the kernels/filters donâ€™t fit, for example because the input image has a width and height\n",
    "#that do not match with the combination of kernel size and stride.\n",
    "\n",
    "# conversion to 2d.\n",
    "\n",
    "detection.add(BatchNormalization())\n",
    "detection.add(Activation('relu'))\n",
    "detection.add(MaxPooling2D(pool_size=(2,2)))\n",
    "detection.add(Dropout(0.25))# to avoid overfitting.\n",
    "\n",
    "#2 -convolutional layer-2\n",
    "detection.add(Conv2D(128,(5,5),padding='same'))\n",
    "detection.add(BatchNormalization())\n",
    "detection.add(Activation('relu'))\n",
    "detection.add(MaxPooling2D(pool_size=(2,2)))\n",
    "detection.add(Dropout(0.25))\n",
    "\n",
    "#3 -convolutional layer-3\n",
    "detection.add(Conv2D(512,(3,3),padding='same'))\n",
    "detection.add(BatchNormalization())\n",
    "detection.add(Activation('relu'))\n",
    "detection.add(MaxPooling2D(pool_size=(2,2)))\n",
    "detection.add(Dropout(0.25))\n",
    "\n",
    "#4 -convolutional layer-4\n",
    "detection.add(Conv2D(1024,(3,3),padding='same'))\n",
    "detection.add(BatchNormalization())\n",
    "detection.add(Activation('relu'))\n",
    "detection.add(MaxPooling2D(pool_size=(2,2)))\n",
    "detection.add(Dropout(0.25))\n",
    "\n",
    "detection.add(Flatten())# to op to 1d array\n",
    "detection.add(Dense(256))# to collecting the op of one layer and passing it to the next layer.\n",
    "detection.add(BatchNormalization())\n",
    "detection.add(Activation('relu'))\n",
    "detection.add(Dropout(0.25))\n",
    "\n",
    "detection.add(Dense(512))\n",
    "detection.add(BatchNormalization())\n",
    "detection.add(Activation('relu'))\n",
    "#The rectified linear activation function or ReLU for short is a piecewise linear function that will output the input directly \n",
    "#if it is positive, otherwise, it will output zero.used for inner layers.\n",
    "detection.add(Dropout(0.25))\n",
    "\n",
    "detection.add(Dense(15,activation='softmax'))# mathematical eq to get the op.\n",
    "#It is mainly used to normalize neural networks output to fit between zero and one.\n",
    "optimum=Adam(lr=0.005) # optimizer used to improve learning rate of the model\n",
    "detection.compile(optimizer=optimum,loss='categorical_crossentropy',metrics=['accuracy'])"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Model: \"sequential\"\n",
      "_________________________________________________________________\n",
      "Layer (type)                 Output Shape              Param #   \n",
      "=================================================================\n",
      "conv2d (Conv2D)              (None, 48, 48, 64)        1792      \n",
      "_________________________________________________________________\n",
      "batch_normalization (BatchNo (None, 48, 48, 64)        256       \n",
      "_________________________________________________________________\n",
      "activation (Activation)      (None, 48, 48, 64)        0         \n",
      "_________________________________________________________________\n",
      "max_pooling2d (MaxPooling2D) (None, 24, 24, 64)        0         \n",
      "_________________________________________________________________\n",
      "dropout (Dropout)            (None, 24, 24, 64)        0         \n",
      "_________________________________________________________________\n",
      "conv2d_1 (Conv2D)            (None, 24, 24, 128)       204928    \n",
      "_________________________________________________________________\n",
      "batch_normalization_1 (Batch (None, 24, 24, 128)       512       \n",
      "_________________________________________________________________\n",
      "activation_1 (Activation)    (None, 24, 24, 128)       0         \n",
      "_________________________________________________________________\n",
      "max_pooling2d_1 (MaxPooling2 (None, 12, 12, 128)       0         \n",
      "_________________________________________________________________\n",
      "dropout_1 (Dropout)          (None, 12, 12, 128)       0         \n",
      "_________________________________________________________________\n",
      "conv2d_2 (Conv2D)            (None, 12, 12, 512)       590336    \n",
      "_________________________________________________________________\n",
      "batch_normalization_2 (Batch (None, 12, 12, 512)       2048      \n",
      "_________________________________________________________________\n",
      "activation_2 (Activation)    (None, 12, 12, 512)       0         \n",
      "_________________________________________________________________\n",
      "max_pooling2d_2 (MaxPooling2 (None, 6, 6, 512)         0         \n",
      "_________________________________________________________________\n",
      "dropout_2 (Dropout)          (None, 6, 6, 512)         0         \n",
      "_________________________________________________________________\n",
      "conv2d_3 (Conv2D)            (None, 6, 6, 1024)        4719616   \n",
      "_________________________________________________________________\n",
      "batch_normalization_3 (Batch (None, 6, 6, 1024)        4096      \n",
      "_________________________________________________________________\n",
      "activation_3 (Activation)    (None, 6, 6, 1024)        0         \n",
      "_________________________________________________________________\n",
      "max_pooling2d_3 (MaxPooling2 (None, 3, 3, 1024)        0         \n",
      "_________________________________________________________________\n",
      "dropout_3 (Dropout)          (None, 3, 3, 1024)        0         \n",
      "_________________________________________________________________\n",
      "flatten (Flatten)            (None, 9216)              0         \n",
      "_________________________________________________________________\n",
      "dense (Dense)                (None, 256)               2359552   \n",
      "_________________________________________________________________\n",
      "batch_normalization_4 (Batch (None, 256)               1024      \n",
      "_________________________________________________________________\n",
      "activation_4 (Activation)    (None, 256)               0         \n",
      "_________________________________________________________________\n",
      "dropout_4 (Dropout)          (None, 256)               0         \n",
      "_________________________________________________________________\n",
      "dense_1 (Dense)              (None, 512)               131584    \n",
      "_________________________________________________________________\n",
      "batch_normalization_5 (Batch (None, 512)               2048      \n",
      "_________________________________________________________________\n",
      "activation_5 (Activation)    (None, 512)               0         \n",
      "_________________________________________________________________\n",
      "dropout_5 (Dropout)          (None, 512)               0         \n",
      "_________________________________________________________________\n",
      "dense_2 (Dense)              (None, 15)                7695      \n",
      "=================================================================\n",
      "Total params: 8,025,487\n",
      "Trainable params: 8,020,495\n",
      "Non-trainable params: 4,992\n",
      "_________________________________________________________________\n"
     ]
    }
   ],
   "source": [
    "detection.summary()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "WARNING:tensorflow:sample_weight modes were coerced from\n",
      "  ...\n",
      "    to  \n",
      "  ['...']\n",
      "WARNING:tensorflow:sample_weight modes were coerced from\n",
      "  ...\n",
      "    to  \n",
      "  ['...']\n",
      "Train for 302 steps, validate for 19 steps\n",
      "Epoch 1/15\n",
      "302/302 [==============================] - 798s 3s/step - loss: 0.9810 - accuracy: 0.6832 - val_loss: 21.3184 - val_accuracy: 0.1094\n",
      "Epoch 2/15\n",
      "302/302 [==============================] - 897s 3s/step - loss: 0.5077 - accuracy: 0.8277 - val_loss: 2.8017 - val_accuracy: 0.4293\n",
      "Epoch 3/15\n",
      "302/302 [==============================] - 787s 3s/step - loss: 0.3713 - accuracy: 0.8768 - val_loss: 8.6086 - val_accuracy: 0.2360\n",
      "Epoch 4/15\n",
      "302/302 [==============================] - 774s 3s/step - loss: 0.2998 - accuracy: 0.8987 - val_loss: 1.3754 - val_accuracy: 0.6760\n",
      "Epoch 5/15\n",
      "302/302 [==============================] - 770s 3s/step - loss: 0.2406 - accuracy: 0.9157 - val_loss: 2.6942 - val_accuracy: 0.5049\n",
      "Epoch 6/15\n",
      "302/302 [==============================] - 801s 3s/step - loss: 0.2109 - accuracy: 0.9270 - val_loss: 1.6531 - val_accuracy: 0.6538\n",
      "Epoch 7/15\n",
      "302/302 [==============================] - 878s 3s/step - loss: 0.1828 - accuracy: 0.9387 - val_loss: 1.5937 - val_accuracy: 0.6760\n",
      "Epoch 8/15\n",
      "302/302 [==============================] - 717s 2s/step - loss: 0.1623 - accuracy: 0.9474 - val_loss: 1.8673 - val_accuracy: 0.6949\n",
      "Epoch 9/15\n",
      "302/302 [==============================] - 1759s 6s/step - loss: 0.1568 - accuracy: 0.9474 - val_loss: 2.0630 - val_accuracy: 0.5477\n",
      "Epoch 10/15\n",
      "302/302 [==============================] - 555s 2s/step - loss: 0.1351 - accuracy: 0.9535 - val_loss: 1.4194 - val_accuracy: 0.6538\n",
      "Epoch 11/15\n",
      "302/302 [==============================] - 551s 2s/step - loss: 0.1332 - accuracy: 0.9550 - val_loss: 0.1892 - val_accuracy: 0.9342\n",
      "Epoch 12/15\n",
      "302/302 [==============================] - 545s 2s/step - loss: 0.1163 - accuracy: 0.9609 - val_loss: 3.8499 - val_accuracy: 0.4334\n",
      "Epoch 13/15\n",
      "302/302 [==============================] - 861s 3s/step - loss: 0.1058 - accuracy: 0.9638 - val_loss: 0.4892 - val_accuracy: 0.8577\n",
      "Epoch 14/15\n",
      "302/302 [==============================] - 524s 2s/step - loss: 0.1122 - accuracy: 0.9608 - val_loss: 0.9248 - val_accuracy: 0.7862\n",
      "Epoch 15/15\n",
      "302/302 [==============================] - 544s 2s/step - loss: 0.1055 - accuracy: 0.9643 - val_loss: 0.3943 - val_accuracy: 0.8956\n"
     ]
    }
   ],
   "source": [
    "ephocs=15 #no of times the model is trained.\n",
    "steps_per_epoch=train_generator.n//train_generator.batch_size\n",
    "steps_per_epoch\n",
    "validation_steps=validation_generator.n//validation_generator.batch_size\n",
    "validation_steps\n",
    "detection.fit(x=train_generator,\n",
    "                    steps_per_epoch=steps_per_epoch,\n",
    "                    epochs=ephocs,\n",
    "                    validation_data=validation_generator,\n",
    "                    validation_steps=validation_steps)\n",
    "detection.save('auto_chloro_model.h5') # saving the trained model,because training of model takes time."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "metadata": {},
   "outputs": [],
   "source": [
    "from tensorflow.keras.preprocessing import image\n",
    "from tensorflow.keras.models import load_model\n",
    "detection=load_model('auto_chloro_model.h5')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "ERROR:root:Internal Python error in the inspect module.\n",
      "Below is the traceback from this internal error.\n",
      "\n",
      "ERROR:root:Internal Python error in the inspect module.\n",
      "Below is the traceback from this internal error.\n",
      "\n",
      "ERROR:root:Internal Python error in the inspect module.\n",
      "Below is the traceback from this internal error.\n",
      "\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\91805\\Anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3444, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"C:\\Users\\91805\\AppData\\Local\\Temp/ipykernel_10028/2384566550.py\", line 1, in <module>\n",
      "    test_img=image.load_img(\"t-spot.jpg\",target_size=(48,48))\n",
      "  File \"C:\\Users\\91805\\Anaconda3\\lib\\site-packages\\keras_preprocessing\\image\\utils.py\", line 113, in load_img\n",
      "    with open(path, 'rb') as f:\n",
      "FileNotFoundError: [Errno 2] No such file or directory: 't-spot.jpg'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\91805\\Anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2064, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'FileNotFoundError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\91805\\Anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1101, in get_records\n",
      "    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)\n",
      "  File \"C:\\Users\\91805\\Anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 248, in wrapped\n",
      "    return f(*args, **kwargs)\n",
      "  File \"C:\\Users\\91805\\Anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 281, in _fixed_getinnerframes\n",
      "    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))\n",
      "  File \"C:\\Users\\91805\\Anaconda3\\lib\\inspect.py\", line 1502, in getinnerframes\n",
      "    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)\n",
      "  File \"C:\\Users\\91805\\Anaconda3\\lib\\inspect.py\", line 1460, in getframeinfo\n",
      "    filename = getsourcefile(frame) or getfile(frame)\n",
      "  File \"C:\\Users\\91805\\Anaconda3\\lib\\inspect.py\", line 696, in getsourcefile\n",
      "    if getattr(getmodule(object, filename), '__loader__', None) is not None:\n",
      "  File \"C:\\Users\\91805\\Anaconda3\\lib\\inspect.py\", line 733, in getmodule\n",
      "    if ismodule(module) and hasattr(module, '__file__'):\n",
      "  File \"C:\\Users\\91805\\Anaconda3\\lib\\site-packages\\tensorflow\\__init__.py\", line 50, in __getattr__\n",
      "    module = self._load()\n",
      "  File \"C:\\Users\\91805\\Anaconda3\\lib\\site-packages\\tensorflow\\__init__.py\", line 44, in _load\n",
      "    module = _importlib.import_module(self.__name__)\n",
      "  File \"C:\\Users\\91805\\Anaconda3\\lib\\importlib\\__init__.py\", line 127, in import_module\n",
      "    return _bootstrap._gcd_import(name[level:], package, level)\n",
      "  File \"<frozen importlib._bootstrap>\", line 1006, in _gcd_import\n",
      "  File \"<frozen importlib._bootstrap>\", line 983, in _find_and_load\n",
      "  File \"<frozen importlib._bootstrap>\", line 965, in _find_and_load_unlocked\n",
      "ModuleNotFoundError: No module named 'tensorflow_core.estimator'\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\91805\\Anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3444, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"C:\\Users\\91805\\AppData\\Local\\Temp/ipykernel_10028/2384566550.py\", line 1, in <module>\n",
      "    test_img=image.load_img(\"t-spot.jpg\",target_size=(48,48))\n",
      "  File \"C:\\Users\\91805\\Anaconda3\\lib\\site-packages\\keras_preprocessing\\image\\utils.py\", line 113, in load_img\n",
      "    with open(path, 'rb') as f:\n",
      "FileNotFoundError: [Errno 2] No such file or directory: 't-spot.jpg'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\91805\\Anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2064, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'FileNotFoundError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\91805\\Anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3364, in run_ast_nodes\n",
      "    if (await self.run_code(code, result,  async_=asy)):\n",
      "  File \"C:\\Users\\91805\\Anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3461, in run_code\n",
      "    self.showtraceback(running_compiled_code=True)\n",
      "  File \"C:\\Users\\91805\\Anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2067, in showtraceback\n",
      "    value, tb, tb_offset=tb_offset)\n",
      "  File \"C:\\Users\\91805\\Anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1368, in structured_traceback\n",
      "    self, etype, value, tb, tb_offset, number_of_lines_of_context)\n",
      "  File \"C:\\Users\\91805\\Anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1268, in structured_traceback\n",
      "    self, etype, value, tb, tb_offset, number_of_lines_of_context\n",
      "  File \"C:\\Users\\91805\\Anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1125, in structured_traceback\n",
      "    tb_offset)\n",
      "  File \"C:\\Users\\91805\\Anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1082, in format_exception_as_a_whole\n",
      "    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)\n",
      "  File \"C:\\Users\\91805\\Anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 382, in find_recursion\n",
      "    return len(records), 0\n",
      "TypeError: object of type 'NoneType' has no len()\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\91805\\Anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2064, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\91805\\Anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1101, in get_records\n",
      "    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)\n",
      "  File \"C:\\Users\\91805\\Anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 248, in wrapped\n",
      "    return f(*args, **kwargs)\n",
      "  File \"C:\\Users\\91805\\Anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 281, in _fixed_getinnerframes\n",
      "    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))\n",
      "  File \"C:\\Users\\91805\\Anaconda3\\lib\\inspect.py\", line 1502, in getinnerframes\n",
      "    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)\n",
      "  File \"C:\\Users\\91805\\Anaconda3\\lib\\inspect.py\", line 1460, in getframeinfo\n",
      "    filename = getsourcefile(frame) or getfile(frame)\n",
      "  File \"C:\\Users\\91805\\Anaconda3\\lib\\inspect.py\", line 696, in getsourcefile\n",
      "    if getattr(getmodule(object, filename), '__loader__', None) is not None:\n",
      "  File \"C:\\Users\\91805\\Anaconda3\\lib\\inspect.py\", line 733, in getmodule\n",
      "    if ismodule(module) and hasattr(module, '__file__'):\n",
      "  File \"C:\\Users\\91805\\Anaconda3\\lib\\site-packages\\tensorflow\\__init__.py\", line 50, in __getattr__\n",
      "    module = self._load()\n",
      "  File \"C:\\Users\\91805\\Anaconda3\\lib\\site-packages\\tensorflow\\__init__.py\", line 44, in _load\n",
      "    module = _importlib.import_module(self.__name__)\n",
      "  File \"C:\\Users\\91805\\Anaconda3\\lib\\importlib\\__init__.py\", line 127, in import_module\n",
      "    return _bootstrap._gcd_import(name[level:], package, level)\n",
      "  File \"<frozen importlib._bootstrap>\", line 1006, in _gcd_import\n",
      "  File \"<frozen importlib._bootstrap>\", line 983, in _find_and_load\n",
      "  File \"<frozen importlib._bootstrap>\", line 965, in _find_and_load_unlocked\n",
      "ModuleNotFoundError: No module named 'tensorflow_core.estimator'\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\91805\\Anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3444, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"C:\\Users\\91805\\AppData\\Local\\Temp/ipykernel_10028/2384566550.py\", line 1, in <module>\n",
      "    test_img=image.load_img(\"t-spot.jpg\",target_size=(48,48))\n",
      "  File \"C:\\Users\\91805\\Anaconda3\\lib\\site-packages\\keras_preprocessing\\image\\utils.py\", line 113, in load_img\n",
      "    with open(path, 'rb') as f:\n",
      "FileNotFoundError: [Errno 2] No such file or directory: 't-spot.jpg'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\91805\\Anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2064, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'FileNotFoundError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\91805\\Anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3364, in run_ast_nodes\n",
      "    if (await self.run_code(code, result,  async_=asy)):\n",
      "  File \"C:\\Users\\91805\\Anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3461, in run_code\n",
      "    self.showtraceback(running_compiled_code=True)\n",
      "  File \"C:\\Users\\91805\\Anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2067, in showtraceback\n",
      "    value, tb, tb_offset=tb_offset)\n",
      "  File \"C:\\Users\\91805\\Anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1368, in structured_traceback\n",
      "    self, etype, value, tb, tb_offset, number_of_lines_of_context)\n",
      "  File \"C:\\Users\\91805\\Anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1268, in structured_traceback\n",
      "    self, etype, value, tb, tb_offset, number_of_lines_of_context\n",
      "  File \"C:\\Users\\91805\\Anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1125, in structured_traceback\n",
      "    tb_offset)\n",
      "  File \"C:\\Users\\91805\\Anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1082, in format_exception_as_a_whole\n",
      "    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)\n",
      "  File \"C:\\Users\\91805\\Anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 382, in find_recursion\n",
      "    return len(records), 0\n",
      "TypeError: object of type 'NoneType' has no len()\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\91805\\Anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2064, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\91805\\Anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2947, in _run_cell\n",
      "    return runner(coro)\n",
      "  File \"C:\\Users\\91805\\Anaconda3\\lib\\site-packages\\IPython\\core\\async_helpers.py\", line 68, in _pseudo_sync_runner\n",
      "    coro.send(None)\n",
      "  File \"C:\\Users\\91805\\Anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3173, in run_cell_async\n",
      "    interactivity=interactivity, compiler=compiler, result=result)\n",
      "  File \"C:\\Users\\91805\\Anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3383, in run_ast_nodes\n",
      "    self.showtraceback()\n",
      "  File \"C:\\Users\\91805\\Anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2067, in showtraceback\n",
      "    value, tb, tb_offset=tb_offset)\n",
      "  File \"C:\\Users\\91805\\Anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1368, in structured_traceback\n",
      "    self, etype, value, tb, tb_offset, number_of_lines_of_context)\n",
      "  File \"C:\\Users\\91805\\Anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1268, in structured_traceback\n",
      "    self, etype, value, tb, tb_offset, number_of_lines_of_context\n",
      "  File \"C:\\Users\\91805\\Anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1143, in structured_traceback\n",
      "    chained_exceptions_tb_offset)\n",
      "  File \"C:\\Users\\91805\\Anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1082, in format_exception_as_a_whole\n",
      "    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)\n",
      "  File \"C:\\Users\\91805\\Anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 382, in find_recursion\n",
      "    return len(records), 0\n",
      "TypeError: object of type 'NoneType' has no len()\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\91805\\Anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2064, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\91805\\Anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1101, in get_records\n",
      "    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)\n",
      "  File \"C:\\Users\\91805\\Anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 248, in wrapped\n",
      "    return f(*args, **kwargs)\n",
      "  File \"C:\\Users\\91805\\Anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 281, in _fixed_getinnerframes\n",
      "    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))\n",
      "  File \"C:\\Users\\91805\\Anaconda3\\lib\\inspect.py\", line 1502, in getinnerframes\n",
      "    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)\n",
      "  File \"C:\\Users\\91805\\Anaconda3\\lib\\inspect.py\", line 1460, in getframeinfo\n",
      "    filename = getsourcefile(frame) or getfile(frame)\n",
      "  File \"C:\\Users\\91805\\Anaconda3\\lib\\inspect.py\", line 696, in getsourcefile\n",
      "    if getattr(getmodule(object, filename), '__loader__', None) is not None:\n",
      "  File \"C:\\Users\\91805\\Anaconda3\\lib\\inspect.py\", line 733, in getmodule\n",
      "    if ismodule(module) and hasattr(module, '__file__'):\n",
      "  File \"C:\\Users\\91805\\Anaconda3\\lib\\site-packages\\tensorflow\\__init__.py\", line 50, in __getattr__\n",
      "    module = self._load()\n",
      "  File \"C:\\Users\\91805\\Anaconda3\\lib\\site-packages\\tensorflow\\__init__.py\", line 44, in _load\n",
      "    module = _importlib.import_module(self.__name__)\n",
      "  File \"C:\\Users\\91805\\Anaconda3\\lib\\importlib\\__init__.py\", line 127, in import_module\n",
      "    return _bootstrap._gcd_import(name[level:], package, level)\n",
      "  File \"<frozen importlib._bootstrap>\", line 1006, in _gcd_import\n",
      "  File \"<frozen importlib._bootstrap>\", line 983, in _find_and_load\n",
      "  File \"<frozen importlib._bootstrap>\", line 965, in _find_and_load_unlocked\n",
      "ModuleNotFoundError: No module named 'tensorflow_core.estimator'\n"
     ]
    }
   ],
   "source": [
    "test_img=image.load_img(\"t-spot.jpg\",target_size=(48,48))\n",
    "# img on which model predicts.\n",
    "plt.imshow(test_img)\n",
    "test_img=image.img_to_array(test_img)\n",
    "test_img=np.expand_dims(test_img,axis=0)\n",
    "result=detection.predict(test_img)\n",
    "a=result.argmax()\n",
    "classes=train_generator.class_indices\n",
    "\n",
    "category=[]\n",
    "for i in classes:\n",
    "          category.append(i)\n",
    "for i in range(len(classes)):\n",
    "           if(i==a):\n",
    "                output=category[i]\n",
    "print(\"Disease :-\" + output)  "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "\n",
    "    \n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "ERROR:root:Internal Python error in the inspect module.\n",
      "Below is the traceback from this internal error.\n",
      "\n",
      "ERROR:root:Internal Python error in the inspect module.\n",
      "Below is the traceback from this internal error.\n",
      "\n",
      "ERROR:root:Internal Python error in the inspect module.\n",
      "Below is the traceback from this internal error.\n",
      "\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\91805\\Anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3444, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"C:\\Users\\91805\\AppData\\Local\\Temp/ipykernel_10028/1248369173.py\", line 1, in <module>\n",
      "    if output == 'Pepper__bell___Bacterial_spot':\n",
      "NameError: name 'output' is not defined\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\91805\\Anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2064, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'NameError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\91805\\Anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1101, in get_records\n",
      "    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)\n",
      "  File \"C:\\Users\\91805\\Anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 248, in wrapped\n",
      "    return f(*args, **kwargs)\n",
      "  File \"C:\\Users\\91805\\Anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 281, in _fixed_getinnerframes\n",
      "    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))\n",
      "  File \"C:\\Users\\91805\\Anaconda3\\lib\\inspect.py\", line 1502, in getinnerframes\n",
      "    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)\n",
      "  File \"C:\\Users\\91805\\Anaconda3\\lib\\inspect.py\", line 1460, in getframeinfo\n",
      "    filename = getsourcefile(frame) or getfile(frame)\n",
      "  File \"C:\\Users\\91805\\Anaconda3\\lib\\inspect.py\", line 696, in getsourcefile\n",
      "    if getattr(getmodule(object, filename), '__loader__', None) is not None:\n",
      "  File \"C:\\Users\\91805\\Anaconda3\\lib\\inspect.py\", line 733, in getmodule\n",
      "    if ismodule(module) and hasattr(module, '__file__'):\n",
      "  File \"C:\\Users\\91805\\Anaconda3\\lib\\site-packages\\tensorflow\\__init__.py\", line 50, in __getattr__\n",
      "    module = self._load()\n",
      "  File \"C:\\Users\\91805\\Anaconda3\\lib\\site-packages\\tensorflow\\__init__.py\", line 44, in _load\n",
      "    module = _importlib.import_module(self.__name__)\n",
      "  File \"C:\\Users\\91805\\Anaconda3\\lib\\importlib\\__init__.py\", line 127, in import_module\n",
      "    return _bootstrap._gcd_import(name[level:], package, level)\n",
      "  File \"<frozen importlib._bootstrap>\", line 1006, in _gcd_import\n",
      "  File \"<frozen importlib._bootstrap>\", line 983, in _find_and_load\n",
      "  File \"<frozen importlib._bootstrap>\", line 965, in _find_and_load_unlocked\n",
      "ModuleNotFoundError: No module named 'tensorflow_core.estimator'\n",
      "ERROR! Session/line number was not unique in database. History logging moved to new session 327\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\91805\\Anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3444, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"C:\\Users\\91805\\AppData\\Local\\Temp/ipykernel_10028/1248369173.py\", line 1, in <module>\n",
      "    if output == 'Pepper__bell___Bacterial_spot':\n",
      "NameError: name 'output' is not defined\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\91805\\Anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2064, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'NameError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\91805\\Anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3364, in run_ast_nodes\n",
      "    if (await self.run_code(code, result,  async_=asy)):\n",
      "  File \"C:\\Users\\91805\\Anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3461, in run_code\n",
      "    self.showtraceback(running_compiled_code=True)\n",
      "  File \"C:\\Users\\91805\\Anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2067, in showtraceback\n",
      "    value, tb, tb_offset=tb_offset)\n",
      "  File \"C:\\Users\\91805\\Anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1368, in structured_traceback\n",
      "    self, etype, value, tb, tb_offset, number_of_lines_of_context)\n",
      "  File \"C:\\Users\\91805\\Anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1268, in structured_traceback\n",
      "    self, etype, value, tb, tb_offset, number_of_lines_of_context\n",
      "  File \"C:\\Users\\91805\\Anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1125, in structured_traceback\n",
      "    tb_offset)\n",
      "  File \"C:\\Users\\91805\\Anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1082, in format_exception_as_a_whole\n",
      "    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)\n",
      "  File \"C:\\Users\\91805\\Anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 382, in find_recursion\n",
      "    return len(records), 0\n",
      "TypeError: object of type 'NoneType' has no len()\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\91805\\Anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2064, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\91805\\Anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1101, in get_records\n",
      "    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)\n",
      "  File \"C:\\Users\\91805\\Anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 248, in wrapped\n",
      "    return f(*args, **kwargs)\n",
      "  File \"C:\\Users\\91805\\Anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 281, in _fixed_getinnerframes\n",
      "    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))\n",
      "  File \"C:\\Users\\91805\\Anaconda3\\lib\\inspect.py\", line 1502, in getinnerframes\n",
      "    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)\n",
      "  File \"C:\\Users\\91805\\Anaconda3\\lib\\inspect.py\", line 1460, in getframeinfo\n",
      "    filename = getsourcefile(frame) or getfile(frame)\n",
      "  File \"C:\\Users\\91805\\Anaconda3\\lib\\inspect.py\", line 696, in getsourcefile\n",
      "    if getattr(getmodule(object, filename), '__loader__', None) is not None:\n",
      "  File \"C:\\Users\\91805\\Anaconda3\\lib\\inspect.py\", line 733, in getmodule\n",
      "    if ismodule(module) and hasattr(module, '__file__'):\n",
      "  File \"C:\\Users\\91805\\Anaconda3\\lib\\site-packages\\tensorflow\\__init__.py\", line 50, in __getattr__\n",
      "    module = self._load()\n",
      "  File \"C:\\Users\\91805\\Anaconda3\\lib\\site-packages\\tensorflow\\__init__.py\", line 44, in _load\n",
      "    module = _importlib.import_module(self.__name__)\n",
      "  File \"C:\\Users\\91805\\Anaconda3\\lib\\importlib\\__init__.py\", line 127, in import_module\n",
      "    return _bootstrap._gcd_import(name[level:], package, level)\n",
      "  File \"<frozen importlib._bootstrap>\", line 1006, in _gcd_import\n",
      "  File \"<frozen importlib._bootstrap>\", line 983, in _find_and_load\n",
      "  File \"<frozen importlib._bootstrap>\", line 965, in _find_and_load_unlocked\n",
      "ModuleNotFoundError: No module named 'tensorflow_core.estimator'\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\91805\\Anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3444, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"C:\\Users\\91805\\AppData\\Local\\Temp/ipykernel_10028/1248369173.py\", line 1, in <module>\n",
      "    if output == 'Pepper__bell___Bacterial_spot':\n",
      "NameError: name 'output' is not defined\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\91805\\Anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2064, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'NameError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\91805\\Anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3364, in run_ast_nodes\n",
      "    if (await self.run_code(code, result,  async_=asy)):\n",
      "  File \"C:\\Users\\91805\\Anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3461, in run_code\n",
      "    self.showtraceback(running_compiled_code=True)\n",
      "  File \"C:\\Users\\91805\\Anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2067, in showtraceback\n",
      "    value, tb, tb_offset=tb_offset)\n",
      "  File \"C:\\Users\\91805\\Anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1368, in structured_traceback\n",
      "    self, etype, value, tb, tb_offset, number_of_lines_of_context)\n",
      "  File \"C:\\Users\\91805\\Anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1268, in structured_traceback\n",
      "    self, etype, value, tb, tb_offset, number_of_lines_of_context\n",
      "  File \"C:\\Users\\91805\\Anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1125, in structured_traceback\n",
      "    tb_offset)\n",
      "  File \"C:\\Users\\91805\\Anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1082, in format_exception_as_a_whole\n",
      "    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)\n",
      "  File \"C:\\Users\\91805\\Anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 382, in find_recursion\n",
      "    return len(records), 0\n",
      "TypeError: object of type 'NoneType' has no len()\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\91805\\Anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2064, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\91805\\Anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2947, in _run_cell\n",
      "    return runner(coro)\n",
      "  File \"C:\\Users\\91805\\Anaconda3\\lib\\site-packages\\IPython\\core\\async_helpers.py\", line 68, in _pseudo_sync_runner\n",
      "    coro.send(None)\n",
      "  File \"C:\\Users\\91805\\Anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3173, in run_cell_async\n",
      "    interactivity=interactivity, compiler=compiler, result=result)\n",
      "  File \"C:\\Users\\91805\\Anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3383, in run_ast_nodes\n",
      "    self.showtraceback()\n",
      "  File \"C:\\Users\\91805\\Anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2067, in showtraceback\n",
      "    value, tb, tb_offset=tb_offset)\n",
      "  File \"C:\\Users\\91805\\Anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1368, in structured_traceback\n",
      "    self, etype, value, tb, tb_offset, number_of_lines_of_context)\n",
      "  File \"C:\\Users\\91805\\Anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1268, in structured_traceback\n",
      "    self, etype, value, tb, tb_offset, number_of_lines_of_context\n",
      "  File \"C:\\Users\\91805\\Anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1143, in structured_traceback\n",
      "    chained_exceptions_tb_offset)\n",
      "  File \"C:\\Users\\91805\\Anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1082, in format_exception_as_a_whole\n",
      "    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)\n",
      "  File \"C:\\Users\\91805\\Anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 382, in find_recursion\n",
      "    return len(records), 0\n",
      "TypeError: object of type 'NoneType' has no len()\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\91805\\Anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2064, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\91805\\Anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1101, in get_records\n",
      "    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)\n",
      "  File \"C:\\Users\\91805\\Anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 248, in wrapped\n",
      "    return f(*args, **kwargs)\n",
      "  File \"C:\\Users\\91805\\Anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 281, in _fixed_getinnerframes\n",
      "    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))\n",
      "  File \"C:\\Users\\91805\\Anaconda3\\lib\\inspect.py\", line 1502, in getinnerframes\n",
      "    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)\n",
      "  File \"C:\\Users\\91805\\Anaconda3\\lib\\inspect.py\", line 1460, in getframeinfo\n",
      "    filename = getsourcefile(frame) or getfile(frame)\n",
      "  File \"C:\\Users\\91805\\Anaconda3\\lib\\inspect.py\", line 696, in getsourcefile\n",
      "    if getattr(getmodule(object, filename), '__loader__', None) is not None:\n",
      "  File \"C:\\Users\\91805\\Anaconda3\\lib\\inspect.py\", line 733, in getmodule\n",
      "    if ismodule(module) and hasattr(module, '__file__'):\n",
      "  File \"C:\\Users\\91805\\Anaconda3\\lib\\site-packages\\tensorflow\\__init__.py\", line 50, in __getattr__\n",
      "    module = self._load()\n",
      "  File \"C:\\Users\\91805\\Anaconda3\\lib\\site-packages\\tensorflow\\__init__.py\", line 44, in _load\n",
      "    module = _importlib.import_module(self.__name__)\n",
      "  File \"C:\\Users\\91805\\Anaconda3\\lib\\importlib\\__init__.py\", line 127, in import_module\n",
      "    return _bootstrap._gcd_import(name[level:], package, level)\n",
      "  File \"<frozen importlib._bootstrap>\", line 1006, in _gcd_import\n",
      "  File \"<frozen importlib._bootstrap>\", line 983, in _find_and_load\n",
      "  File \"<frozen importlib._bootstrap>\", line 965, in _find_and_load_unlocked\n",
      "ModuleNotFoundError: No module named 'tensorflow_core.estimator'\n"
     ]
    }
   ],
   "source": [
    "if output == 'Pepper__bell___Bacterial_spot':\n",
    "        print('''Bacterial spot disease of bell pepper / capsicum \\n\n",
    "         Biological control: n nBacterial stain control is very complex and expensive. \n",
    "If the disease occurs at the beginning of the season, it is better to destroy the entire crop. \n",
    "Copper-rich antibacterial, forms a protective coating on fruits and petals. \n",
    "Antibiotics for bacterial viruses (bacteriophages) are available on the market that kill certain bacteria. \n",
    "Soak the seeds in 1.3% sodium hypochlorite solution for 1 minute or in hot water (50 C) for 25 minutes. \n",
    "\\n \\n Chemical control:\n",
    " \\n \\n Always take preventive measures through biological control under integrated pest management as much as possible. \n",
    "Only copper-containing antibacterial agents can prevent and partially control the disease. \n",
    "Spray as soon as the disease appears, and apply every 10-14 days in warm and humid environment. \n",
    "Mixed pesticides rich in mancozeb and copper may provide some protection.''')\n",
    "        \n",
    "elif output == 'Potato___Early_blight':\n",
    "        print( '''Potato early blight disease\\n\n",
    "        Biological control: n nBacillus subtilis composite material or copper-based.\n",
    "Recognized as an organic fungicide that can be applied against this disease.\n",
    "\\n \\nChemical control:\n",
    " \\n\\nPrevent prevention through biological control under possible pest management. \n",
    "There are different types of fungicides available in the market which can control potato blight. \n",
    "Azoxitrobin, pyroclostrobin, diphenconazole, boscalid, chlorothalonil, phenamidone, maneb, mancozeb, trifloxistrobin,.\n",
    "And fungicides like germination etc. are used to control the disease. \n",
    "It is recommended to use different types of chemical mixtures periodically. Finish all attendance on time in suitable weather. A\n",
    "After applying these ingredients, take a break before harvest to be safe for health.''')\n",
    "        \n",
    "elif output == 'Potato___Late_blight':\n",
    "        print( '''Potato Nabi Dhwasa Rog \\n\n",
    "        Biological control: n nApply a copper based fungicide before the onset of dry weather. \n",
    "Infection can also be prevented by spraying organic coating on the leaves. \n",
    "\\n \\n Chemical control:\n",
    "\\n\\n Always take preventive measures through biological control under integrated pest management. A\n",
    "It is important to use fungicides to control nematodes everywhere in the field, especially in humid parts. A\n",
    "The corresponding fungicide that covers the leaves is very effective before infection and does not allow the fungus to develop resistance to the fungicide. A\n",
    "Mandipropamid, chlorothalonil, fluazinam, for preventive measures.\n",
    "Triphenyltin, or mancozeb fungicides can be used.\n",
    "It is also possible to purify the seeds with fungicides like Mancozeb before sowing.''')\n",
    "        \n",
    "elif output == 'Tomato_Bacterial_spot':\n",
    "        print('''Tomato Bacterial Disease\n",
    "        Biological control: \\n \\nBacterial spot control is very difficult and expensive. \n",
    "If the disease attacks at the beginning of the season, it destroys the whole land. Bactericidal copper content.\n",
    "The leaves and fruit are used as an antidote. Bacteriophages (bacteriophages) that kill bacteria.\n",
    "It is available all the time. 1.3% sodium hypochlorite in one minute or in hot water (50 C) for 25 minutes.\n",
    "Soaking the seeds can reduce the spread of the disease. \n",
    "\\n \\nChemical control:\n",
    "\\n\\nPrevent disease control through biological control under integrated pest management as much as possible. \n",
    "Copper is used as a bactericidal and antiseptic.\n",
    "Can provide control. Apply bactericide as soon as the first symptoms appear and.\n",
    "Then apply warm [small spots / cold (spots)], 10 to 14 days in case of humid weather. \n",
    "Since the constant use of copper builds up a bactericidal immune system, copper is a synthetic substance.\n",
    "It is recommended to use Mancozeb with bactericide.''')\n",
    "        \n",
    "elif output == 'Tomato_Early_blight':\n",
    "        print('''Tomato early blight\n",
    "        Biological control: n nBacillus subtilis composite material or copper-based.\n",
    "Recognized as an organic fungicide that can be applied against this disease. A\n",
    "\\n \\nChemical control:\n",
    "\\n \\n\n",
    "Prevent prevention through biological control under possible pest management. \n",
    "There are different types of fungicides available in the market which can control potato blight. \n",
    "Azoxitrobin, pyroclostrobin, diphenconazole, boscalid, chlorothalonil, phenamidone, maneb, mancozeb, trifloxistrobin,.\n",
    "And fungicides like germination etc. are used to control the disease. \n",
    "It is recommended to use different types of chemical mixtures periodically. Finish all attendance on time in suitable weather. \n",
    "After applying these ingredients, take a break before harvest to be safe for health.''')\n",
    "        \n",
    "        \n",
    "elif output == 'Tomato_Late_blight':\n",
    "        print( '''Tomato's nasal decay disease'\n",
    "        Biological control:à¥¤ n nThere are no known biological measures against nephritis to date. \n",
    "To prevent the spread of the disease, immediately remove or destroy the crop from the infected area and the infected crop.\n",
    "Refrain from making organic manure. \n",
    "\\n \\n Chemical control:\n",
    " n \\ n Take integrated pest management to prevent disease through biological control. \n",
    "Spray fungicides containing Mandipropamide, Chlorothalonil, Fluazineum, and Mancozeb Organized Ingredients to prevent neoplasms. \n",
    "If watering is done from the top of the tree or during the rainy season of the year, it is necessary to apply fungicide.''')\n",
    "        \n",
    "elif output == 'Tomato_Leaf_Mold':\n",
    "        print('''Tomato Leaf Fungus Disease \\n\n",
    "        Biological control: \\n \\nHot water for disinfection (25 minutes at 122 degrees Fahrenheit or 50 degrees Celsius).\n",
    "There are suggestions to purify the seeds with. Acronium strictum, Dysima palvinata, Trichoderma harzinum.\n",
    "Or Trichoderma viridi and Trichothesium rosium fungi Mycovelosila falvar are enemies and can be used to control them.\n",
    "In greenhouses Acremonium strictum, Trichoderma viridi strain 3 and Trichothesium rosium are 53, 6 and 64 percent respectively.\n",
    "Mycovelosila falwa of tomato is suppressed by rate application. On a small scale, mix apple cider, garlic or milk and vinegar.\n",
    "It can be used to control the fungus. \n",
    "\\n \\n Chemical control:\n",
    "\\n \\nAlways take preventive measures through biological control under integrated pest management as much as possible. If the weather is favorable for the disease to spread.\n",
    "Fungicide should be sprayed before infection. Chlorothalonil, maneb, mancozeb and.\n",
    "Copper fungicides are recommended for use in the field. Difenoconazole for greenhouses.\n",
    "Mandipropamid, cymoxanil, famoxadone and cyprodinil.\n",
    "Use is recommended.''')\n",
    "        \n",
    "    \n",
    "elif output == 'Tomato_Septoria_leaf_spot':\n",
    "        print('''Biological control: n nSeptoria spot disease of tomatoes \n",
    "        Copper fungicides, such as Bordeaux mixture, copper hydroxide, copper sulphate,.\n",
    "Or copper oxychloride sulfate can help control the germs of the disease.\n",
    "Spray every 8 to 10 days throughout the season, especially during flowering and fruiting.\n",
    "Follow the rules written on the pesticide packaging before harvesting. A\n",
    "n nChemical control:\n",
    "n nPrevent prevention through biological control under possible integrated pest management. I mean, six.\n",
    "The fungicides Mancozeb and Chlorothalonil are effective in controlling tomato septoria. A\n",
    "Spray at intervals of 8 to 10 days throughout the season, especially during flowering and fruiting. A\n",
    "Follow the rules written on the pesticide packaging before harvesting.''')\n",
    "        \n",
    "elif output == 'Tomato_Spider_mites_Two_spotted_spider_mite':\n",
    "        print('''Normal Red Spider \\n\n",
    "        Biological control: \\n \\n With a slight attack, just wash the spider off with water and remove the infected leaf. A\n",
    "Prepare a mixture of castor oil, basil, soybean and neem oil. Spray the leaves to reduce the reproduction of RTC. A\n",
    "Reproduction of spiders can also be reduced by using a solution of garlic tea, nettle leaf bark or insecticide soap. A\n",
    "Depending on the species of spider in the field, use predatory spiders with biological controllers (for example, Phytoceiulus persimilis).\n",
    "Or use the organic pesticide Bacillus thuringiensis. It is important to apply a second spray 2-3 days after the initial spray. A\n",
    "\\n \\n Chemical control:\n",
    "n \\ nAlways take preventive measures through biological control under integrated pest management as much as possible. A\n",
    "These spiders are very difficult to control with poisonous substances because they have been used for several years in most generations.\n",
    "Resistance to various chemicals is developed. Carefully select the chemical controller to control the predators of this spider.\n",
    "It does not destroy indiscriminately. Examples are water-soluble sulfur (3 g / liter), spiromycin (1 ml / liter).\n",
    "Dicofol (5 ml / liter) or abamectin-rich fungicides can be used. Second time 2 to 3 days after initial spray.\n",
    "It is important to apply the spray.''')\n",
    "        \n",
    "elif output == 'Tomato__Target_Spot':\n",
    "        print('''Tomato Target Disease \\n\n",
    "        Watering in the morning so that the leaves of the tomato plant have time to dry. Water or dry the leaves at the base of the tree.\n",
    "Use a hose or drip system for. Apply a sesame to monitor the fruit from direct contact with the soil. ''')\n",
    "        \n",
    "elif output == 'Tomato__Tomato_mosaic_virus images':\n",
    "        print('''Tomato mosaic virus disease \\n\n",
    "        Biological control: \\n  for 4 days or 72-75 Â° C for 24 hours dry.\n",
    "Heating and purifying the seeds helps to keep the seeds virus free. Alternatively, 100 g / liter.\n",
    "Soak the seeds in a solution of trisodium phosphate for 15 minutes and rinse thoroughly with water.\n",
    "Even if it is dried later, it works. \n",
    "\\n \\n Chemical control:\n",
    " n \\ nTake preventive measures through biological control as much as possible under integrated pest management. A\n",
    "There is no effective chemical pest management for tomato mosaic virus.''')\n",
    "        \n",
    "elif output == 'Tomato__Tomato_YellowLeaf__Curl_Virus images':\n",
    "        print('''Tomato yellow leaf curl virus disease\n",
    "        Biological control: n nTome yellow tomato leaf curl virus (TYLCV) disease.\n",
    "No repression is known. Control whitefly breeding to avoid virus attacks. \n",
    "\\n \\nChemical control:\n",
    "\\n \\n Once infected with the virus, no further control measures work against it. \n",
    "Whitefly breeding needs to be controlled to avoid virus attacks. \n",
    "Pyrethroids are a class of insecticides used by plants to fertilize plants or soil.\n",
    "Reproduction can be reduced. But excessive use of these can increase the immunity of simple fish.''')\n",
    "        \n",
    "elif output == 'Pepper__bell___healthy' or output == 'Potato___healthy' or output == 'Tomato_healthy':\n",
    "        print( 'healthy')\n",
    "        "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.7.6"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
